type Opening {
  fen: String! @unique
  SCID: String!
  desc: String!
}

type Game {
  header: Header! 
  fens: [String!]!
  opening: Opening @relation
}

type Header {
    event: String!
    date: String!
    white: String!
    black: String!
    eco: String!
}

type Query {
  allGames: [Game]
  allOpenings: [Opening]
}

input OpeningInput {
  fen: String!
  SCID: String!
  desc: String!
}

type Mutation {
  addOpenings(openings: [OpeningInput]) : [Opening]! @resolver(name: "add_openings2")
}